added detection for IPv4
NCATComp410/comp410_summer_2023 pull request #26
Opened 2023-06-28 00:21 UTC by aalston2

2023-06-28 01:03 UTC, daseanneclos approved these changes

2023-06-28 22:03 UTC, claesmk requested changes
I still see NRP which should be IP_ADDRESS

2023-06-28 22:03 UTC, claesmk commented on test_pii_scan.py
> +        self.assertNotIn('NRP', str(results))
I think you meant to say IP_ADDRESS here not NRP

2023-06-28 22:32 UTC, aalston2 commented on test_pii_scan.py
> +        self.assertNotIn('NRP', str(results))
thank you for letting me know I will adjust this mistake

2023-06-29 01:21 UTC, claesmk approved these changes
Looks good

2023-06-29 03:02 UTC, nsmiller1 approved these changes
Looks fine to me. I'm curious though why only one self.assertIn for the results

2023-06-29 13:25 UTC, claesmk commented
@aalston2 this looks ready for you to merge and delete your branch and Codespace

2023-06-30 03:50 UTC, merged